- name: Ensure ansible user exists
  user:
    name: ansible
    shell: /bin/bash
    create_home: yes

- name: Install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/UNT-Unified-Endpoints/Ansible.git > /dev/null"
