- name: Gather service facts
  ansible.builtin.service_facts:

- name: Decide if ConnectWise/ScreenConnect is installed
  ansible.builtin.set_fact:
    cwc_installed: >-
      {{
        (
          ansible_facts.services
          | dict2items
          | selectattr('key','search','(?i)(connectwisecontrol|screenconnect)')
          | selectattr('value.state','equalto','running')
          | list | length
        ) > 0
        or
        (
          ansible_facts.services
          | dict2items
          | selectattr('key','search','(?i)(connectwisecontrol|screenconnect)')
          | selectattr('value.status','equalto','enabled')
          | list | length
        ) > 0
      }}

- name: Debug detection
  ansible.builtin.debug:
    msg: "ScreenConnect is {{ 'installed (running/enabled)' if cwc_installed else 'not installed (stopped/disabled or absent)' }}"

- name: Install ScreenConnect if missing
  ansible.builtin.script: files/ScreenConnect.ClientSetup.sh
  when: not cwc_installed
