- name: Gather service facts
  ansible.builtin.service_facts:

- name: Look for existing install directory
  ansible.builtin.find:
    paths: /opt
    patterns: "connectwisecontrol-*"
    file_type: directory
  register: cwc_dir

- name: Decide if ConnectWise/ScreenConnect is installed
  ansible.builtin.set_fact:
    cwc_installed: >-
      {{
        (
          ansible_facts.services
          | dict2items
          | selectattr('key','search','(?i)(connectwisecontrol|screenconnect)')
          | list | length
        ) > 0
        or (cwc_dir.matched | default(0) | int) > 0
      }}

- name: Show status of ConnectWise detection
  ansible.builtin.debug:
    msg: >
      ConnectWise/ScreenConnect is {{
        'already installed' if cwc_installed else 'not installed, will install'
      }}

- name: Install ScreenConnect if missing
  ansible.builtin.script: files/ScreenConnect.ClientSetup.sh
  when: not cwc_installed
